services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./docker/nginx/nginx_proxy.conf:/etc/nginx/conf.d/nginx_proxy.conf:ro
      - ./:/var/www/app
    depends_on:
      - php-fpm
    networks:
      - default

  php-fpm:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/app
    command: [ "/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/supervisord.conf" ]
    depends_on:
      - mysql
    networks:
      - default
    healthcheck:
      test: mysqladmin ping -h mysql -u ${DB_USERNAME} --password=${DB_PASSWORD}
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/create-database.sh:/docker-entrypoint-initdb.d/create-database.sh
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
    networks:
      - default

volumes:
  mysql_data:
    name: ${VOLUME_MYSQL_LIB}
    external: true
