services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./docker/nginx/nginx_proxy.conf:/etc/nginx/conf.d/nginx_proxy.conf:ro
      - ./:/var/www/app
    depends_on:
      - php-fpm
    networks:
      - default

  php-fpm:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/app
    command: [ "/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/supervisord.conf" ]
    depends_on:
      - mysql
    networks:
      - default

  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - default

volumes:
  mysql_data:
    name: ${VOLUME_MYSQL_LIB}
    external: true
  redis_data:
    name: ${VOLUME_REDIS_DATA}
    external: true
