services:
  nginx:
    restart: always
    networks:
      - publish

  php-fpm:
    restart: always

  mysql:
    restart: always

  redis:
    restart: always

networks:
  publish:
    external: true
    name: ${NGINX_CLOUD_NETWORK}
