openapi: 3.0.9
info:
  title: Zuu REST API
  version: 1.0.0
servers:
  - url: localhost:8080/api
paths:
  /login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  required: true
                password:
                  type: string
                  required: true
      responses:
        '200':
          description: Một mảng các object thông báo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Access Token'

  /get-profile-user/{user-id}:
    get:
      parameters:
        -
          name: user-id
          in: path
          description: Id người dùng
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Thông tin người dùng
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"

components:
  schemas:
    Access Token:
      type: object
      properties:
        access_token:
          type: string
          required: true
        expires_in:
          type: integer
          required: true

    User:
      type: object
      items:
        properties:
          first_name:
            type: string
          last_name:
            type: string
          designation:
            type: string
          website:
            type: string
          phone:
            type: string
          email:
            type: string
          joining_date:
            type: string
          about:
            type: string
