openapi: 3.0.9
info:
  title: Zuu REST API
  version: 1.0.0
servers:
  - url: localhost:8080/api
paths:
  /login:
    post:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  required: true
                password:
                  type: string
                  required: true
      responses:
        '200':
          description: Một mảng các object thông báo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Access Token'

  /get-profile-user/{user-id}:
    get:
      tags:
        - Users
      parameters:
        - name: user-id
          in: path
          description: Id người dùng
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Thông tin người dùng
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"

  /projects:
    get:
      tags:
        - Projects
      parameters:
        - name: page
          in: query
          description: Số trang cần lấy
          schema:
            type: number
        - name: limit
          in: query
          description: Số dự án trong một trang
          schema:
            type: number
      responses:
        200:
          description: Danh sách các dự án của người dùng
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Project"
        401:
          description: Không có quyền truy cập nguồn dữ liệu
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    Access Token:
      type: object
      properties:
        access_token:
          type: string
          required: true
        expires_in:
          type: integer
          required: true

    User:
      type: object
      properties:
        first_name:
          type: string
          required: true
        last_name:
          type: string
          required: true
        designation:
          type: string
        website:
          type: string
        phone:
          type: string
        email:
          type: string
          required: true
        joining_date:
          type: string
          required: true
        about:
          type: string
        avatar:
          type: string
          required: true

    Project:
      type: object
      properties:
        uuid:
          type: string
          required: true
        name:
          type: string
          required: true
        description:
          type: string
        summary:
          type: string
        icon:
          type: string
          required: true
        is_favorites:
          type: string
          required: true
        status:
          type: string
          required: true
        priority:
          type: string
          required: true
