name: Zuu backend
on: push
jobs:
  Testcase:
    runs-on: ubuntu-latest
    name: Testcase
    steps:
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Copy docker compose
        run: php -r "file_exists('docker-compose.override.yml') || copy('docker-compose-local.yml', 'docker-compose.override.yml');"
#      - name: Set alias sail
#        shell: bash
#        run: |
#          echo 'shopt -s expand_aliases'  > ~/.bashrc
#          echo "alias sail='./vendor/bin/sail '" >> ~/.bashrc
#      - name: Up sail
#        shell: bash
#        run: |
#          source ~/.bashrc
#          sail up -d
#      - name: Run test
#        run: |
#          source ~/.bashrc
#          sail test
