name: Zuu backend
on: push
jobs:
  Test:
    runs-on: ubuntu-latest
    name: Testcase
    steps:
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Copy docker compose
        run: php -r "file_exists('docker-compose.override.yml') || copy('docker-compose-local.yml', 'docker-compose.override.yml');"
      - name: Build docker image
        run: docker compose build
      - name: Run test
        run: docker compose exec -it php-fpm php artisan test
#      - name: Up sail
#        shell: bash
#        run: |
#          source ~/.bashrc
#          sail up -d
#      - name: Run test
#        run: |
#          source ~/.bashrc
#          sail test
